### ISSUE TITLE
How to install “win32event” module package from pypi # ERROR  “pip install win32event” is not available. Thanks！

### ISSUE THREAD

**Issue by chunweizhu** [tomleung1996/wos_crawler#16]
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from gui.main_gui import *
  File "D:\GitDownload\wos_crawler\wos_crawler\gui\main_gui.py", line 6, in <module>
    import qt5reactor
  File "C:\Users\chunweizhu\AppData\Local\Programs\Python\Python37\lib\site-packages\qt5reactor\__init__.py", line 1, in <module>
    from qt5reactor.core import install, QtReactor
  File "C:\Users\chunweizhu\AppData\Local\Programs\Python\Python37\lib\site-packages\qt5reactor\core.py", line 399, in <module>
    from win32event import CreateEvent, MsgWaitForMultipleObjects
ModuleNotFoundError: No module named 'win32event'

pip install win32event
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement win32event (from versions: none)
ERROR: No matching distribution found for win32event
WARNING: You are using pip version 20.1.1; however, version 20.2.2 is available.
You should consider upgrading via the 'c:\users\chunweizhu\appdata\local\programs\python\python37\python.exe -m pip install --upgrade pip' command.

**python version：3.6
win10
use prwershell command**

**Comment by chunweizhu** [comment]
Not install pywin32 module.
you need pip install pywin32
done!
[](http://timgolden.me.uk/pywin32-docs/PyWin32.html)
